spring.application.name=Flat-Radar

spring.datasource.url=jdbc:postgresql://localhost:5432/flatradar_db
spring.datasource.username=postgres
spring.datasource.password=naveen

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey
jwt.expiration=3600000